### ISSUE TITLE
Input and Output filtering, validation and sanitisation

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#1]
Following Karl's risk assessment a few issues have been noted. 
Please refer to the ticket #026 on basecamp and make the necessary adjustments. 
https://3.basecamp.com/5557999/buckets/31472726/card_tables/cards/5909054045

**Comment by anicapetrovicwlv** [comment]
Added prepared statements to the Database class.
https://github.com/mohammedGrech/Biometric-PasswordVaultManager/blob/ParameterizedSQL/app/src/main/java/com/example/secure/Database.java

`// Adds a website record to the "Websites" table in the database

    public boolean addRecord(WebsiteModel websiteModel){
    
        SQLiteDatabase db = this.getWritableDatabase();
        String sql = "INSERT INTO " + TABLE_WEBSITES + " (" + WEB_NAME + ", " + WEB_URL + ", " + WEB_username + ", " + WEB_PASSWORD + ", " + WEB_NOTE + ", " + WEB_LOGO + ") VALUES (?, ?, ?, ?, ?, ?)";
        SQLiteStatement statement = db.compileStatement(sql);

        statement.bindString(1, websiteModel.getName());
        statement.bindString(2, websiteModel.getUrl());
        statement.bindString(3, websiteModel.getusername());
        statement.bindString(4, websiteModel.getPassword());
        statement.bindString(5, websiteModel.getNote());
        statement.bindString(6, websiteModel.getWeb_logo());

        long insert = statement.executeInsert();
        if (insert == -1){
            return false;
        }
        else {
            return true;
        }
    }
    
    // Update record
    @SuppressLint("RestrictedApi")
    void updateData(Integer row_id, String name, String email, String password, String url, String note, String webLogo) {
        try {
            SQLiteDatabase db = this.getWritableDatabase();
            String sql = "UPDATE " + TABLE_WEBSITES + " SET " + WEB_NAME + " = ?, " + WEB_URL + " = ?, " + WEB_username + " = ?, "
                    + WEB_PASSWORD + " = ?, " + WEB_NOTE + " = ?, " + WEB_LOGO + " = ? WHERE " + WEB_ID + "=" + row_id;

            SQLiteStatement statement = db.compileStatement(sql);

            statement.bindString(1, name);
            statement.bindString(2, url);
            statement.bindString(3, email);
            statement.bindString(4, password);
            statement.bindString(5, note);
            statement.bindString(6, webLogo);

            statement.executeUpdateDelete();
        }catch (android.database.sqlite.SQLiteConstraintException exception){
            Log.d(TAG, "failure to update word,", exception);
        }
    }
    
     /* Deletes a website record from the "Websites" table */
    public boolean deleteRecord(int webID){
        SQLiteDatabase db = this.getWritableDatabase();
        String sql = "DELETE FROM " + TABLE_WEBSITES + " WHERE " + WEB_ID + " = ?";
        SQLiteStatement statement = db.compileStatement(sql);

        statement.bindLong(1, webID);

        long delete = statement.executeUpdateDelete();
        if (delete == -1){
            return false;
        }
        else {
            return true;
        }
    }

**Comment by anicapetrovicwlv** [comment]
accidentally closed the issue

**Comment by mohammedGrech** [comment]
Regex expressions were used to validate user inputs for the password field as follows:

private static final Pattern PASSWORD_PATTERN =
            Pattern.compile("^" +
                    "(?=.*[0-9])" +         //at least 1 digit
                    "(?=.*[a-z])" +         //at least 1 lower case letter
                    "(?=.*[A-Z])" +         //at least 1 upper case letter
                    "(?=.*[a-zA-Z])" +      //any letter
                    "(?=.*[!@#$%^&*()_+=<>?/{}~|])" +    //at least 1 special character
                    "(?=\\S+$)" +           //no white spaces
                    ".{4,}" +               //at least 4 characters
                    `"$");`
//Validate Password
    private boolean validatePassword() {
        String passwordInput = recordPassword.getText().toString().trim();

        if (passwordInput.isEmpty()) {
            recordPassword.setError("Field cannot be empty");
            return false;
        } else if (!PASSWORD_PATTERN.matcher(passwordInput).matches()) {
            recordPassword.setError("Password must include a symbol, an uppercase, a lowercase, and a digit");
            return false;
        } else {
            recordPassword.setError(null);
            return true;
        }
    }

Input validation was also done for the rest of the fields as follows:

  //Validate Name
    private boolean validateName() {
        String nameInput = recordName.getText().toString().toString().trim();

        if (nameInput.isEmpty()) {
            recordName.setError("Field cannot be empty");
            return false;
        } else {
            recordName.setError(null);
            return true;
        }
    }

    //Validate Email
    private boolean validateEmail() {
        String emailInput = recordEmail.getText().toString().trim();

        if (emailInput.isEmpty()) {
            recordEmail.setError("Field cannot be empty");
            return false;
        } else if (!Patterns.EMAIL_ADDRESS.matcher(emailInput).matches()) {

            recordEmail.setError("Email is not valid");
            return false;
        } else {
            recordName.setError(null);
            return true;
        }
    }

    //Validate URL
    private boolean validateWebURL() {
        String webUrlInput = recordWebLink.getText().toString().trim();

        if (webUrlInput.isEmpty()) {
            recordWebLink.setError("Field cannot be empty");
            return false;
        } else if (!Patterns.WEB_URL.matcher(webUrlInput).matches()) {
            recordWebLink.setError("Web link is not valid");
            return false;
        } else {
            recordWebLink.setError(null);
            return true;
        }
    }
