### ISSUE TITLE
Keyboard overlays the note text box

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#14]
When the user taps on the note text box, the keyboard opens and overlays it.
![KeyboardOverlaysNoteBox](https://user-images.githubusercontent.com/126191597/232579958-4cd39344-45f3-455b-bd37-4f87e9cfb988.png)

**Comment by mohammedGrech** [comment]
This issue has been sorted by adding the following script to the related layout:

android:windowSoftInputMode="adjustPan" 

![image](https://user-images.githubusercontent.com/124829903/233423987-c94f0b5d-4112-49cb-9242-d7ac98aa2742.png)
