### ISSUE TITLE
Redirected to the main screen

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#15]
When adding and updating a record the user should be redirected to the main screen.

**Comment by mohammedGrech** [comment]
This enhancement has been completed by adding the following code to both register and update classes:

Intent intent = new Intent(v.getContext(),HomeActivity.class);
startActivity(intent);

This update is also available in the latest push to GitHub which was today 24/04/2023
