### ISSUE TITLE
Notification bar when adding a record

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#16]
The notification bar is showing a string with the information being added rather than a text that says a record has been added. 

![image](https://user-images.githubusercontent.com/126191597/234066588-4575f2d7-fe14-447e-8292-0334e5bc3b09.png)

**Comment by mohammedGrech** [comment]
The above has been replaced with the following message:
![image](https://user-images.githubusercontent.com/124829903/234079832-6a890db5-b18d-4a23-bfd9-042e6a4bc312.png)
