### ISSUE TITLE
Create a privacy policy page

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#17]
The privacy policy explains how the application handles the users information gathered in its operations.
 
Please refer to the ticket #028 on basecamp for the vulnerability assessment of the security consultant.
https://3.basecamp.com/5557999/buckets/31472726/card_tables/cards/5915678228

**Comment by mohammedGrech** [comment]
As per the below ticket on Basecamp, this policy has already been created:
https://3.basecamp.com/5557999/buckets/31472726/card_tables/cards/5909267562
![image](https://user-images.githubusercontent.com/124829903/234661580-16031e61-028b-4ba3-8a2c-86bfa38b6e16.png)
