### ISSUE TITLE
Replace any entries of USE_FINGERPRINT with USE_BIOMETRIC

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#18]
The entries of USE_FINGERPRINT should be replaced with USE_BIOMETRIC

Please refer to the ticket #028 on basecamp for the vulnerability assessment of the security consultant.
https://3.basecamp.com/5557999/buckets/31472726/card_tables/cards/5915678228

**Comment by mohammedGrech** [comment]
USE_FINGERPRINT has been replaced by USE_BIOMETRIC where modification was allowed. On certain codes, the default name is USE_FINGERPRINT:
![image](https://user-images.githubusercontent.com/124829903/234680301-9435d0c9-b09d-4b99-b065-9ec2587ced35.png)
