### ISSUE TITLE
Enabled Application Backup [Medium]

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#19]
ENABLED APPLICATION BACKUP [Medium]
To change code from android:allowBackup="true" to android:allowBackup="false"

Please refer to the ticket #028 on basecamp for the vulnerability assessment of the security consultant.
https://3.basecamp.com/5557999/buckets/31472726/card_tables/cards/5915678228

**Comment by mohammedGrech** [comment]
Allow backup has been set up to “false” as per below:
![image](https://user-images.githubusercontent.com/124829903/234660865-61526f62-9295-412c-9245-25243e1fe42c.png)
