### ISSUE TITLE
Improper Platform Usage 

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#2]
Being aware of flaws in the O/S and applying countermeasures.

Please refer to the ticket #025 on basecamp for the risk assessment of the security consultant.
https://3.basecamp.com/5557999/buckets/31472726/card_tables/cards/5909045847

**Comment by mohammedGrech** [comment]
Per our group discussion, Improper Platform Usage shall be considered later in development due to other implementations that have higher priority.

@Jmiffy97 You may proceed with opening a ticket in the backlog for future implementation.
