### ISSUE TITLE
Password too weak label should be more user friendly 

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#22]
When the users enters a weak password the application should notify that the user must enter a minimum of 4 characters including a symbol, uppercase , lowercase and a digit. 

![WeakPasswordLabel](https://user-images.githubusercontent.com/126191597/234921558-7c7e4bb0-7639-433e-b274-0ec68bd62865.png)

**Comment by mohammedGrech** [comment]
The error description has been enhanced as follows:

![image](https://user-images.githubusercontent.com/124829903/234926894-9d1718cb-533f-452d-a222-5314d4c7961c.png)
