### ISSUE TITLE
Dependency Confusion

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#6]
Before downloading and installing an external software be aware that it is safe and authentic.

Please refer to the ticket #025 on basecamp for the risk assessment of the security consultant
https://3.basecamp.com/5557999/buckets/31472726/card_tables/cards/5909045847

**Comment by mohammedGrech** [comment]
Our repository is private and we only use Android native libraries such as Biometric authentication. Therefore closing this ticket since it's irrelevant.

**Comment by mohammedGrech** [comment]
Further to the above, I have also tested and successfully installed the last update of the APK on my phone without the need for Internet connectivity. There was no missing functionality from the application
![4197e090-ed02-4050-a1c2-e0e0f948692f](https://user-images.githubusercontent.com/124829903/231525603-9dbca5ca-af4d-4310-ba7d-34d24915fc36.jpg)
![76300487-ed21-410a-93b2-8b09215eddef](https://user-images.githubusercontent.com/124829903/231525630-198a87b1-4133-457a-9793-eca188b33006.jpg)
![eb8be876-3c40-447a-b230-9486ec291938](https://user-images.githubusercontent.com/124829903/231525718-ef55ccbc-eeec-498e-a691-880e02dfe103.jpg)
![a3ca0a59-b4f0-4613-a353-c8120f99949b](https://user-images.githubusercontent.com/124829903/231525738-342bd835-6988-4bf0-b80d-5ab6135fa168.jpg)
