### ISSUE TITLE
Improper Session Handling

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#8]
Sessions should be handled well by using inactive timeouts and application state awareness.

Please refer to the ticket #025 on basecamp for the risk assessment of the security consultant
https://3.basecamp.com/5557999/buckets/31472726/card_tables/cards/5909045847

**Comment by mohammedGrech** [comment]
This issue has been resolved by forcing the application to move back to the login page as soon as the user exits the app

    // Once the app is destroy (user exit from the app)
    @Override
    protected void onDestroy() {
        super.onDestroy();
        Intent intentMain = new Intent(this, MainActivity.class); // move back to the main page which contains the biometric login 
        this.startActivity(intentMain);
        finish(); // exit the system
        System.exit(0); // exit the system
    }
