### ISSUE TITLE
Duplicate Instagram in the icon list

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#9]
When testing the application I found that in the dropdown icon selection Instagram is duplicate.
![Testing_DuplicateInstagram](https://user-images.githubusercontent.com/126191597/229601851-c34732df-51d5-4bec-b781-48f8ea44bdde.jpg)

**Comment by mohammedGrech** [comment]
This issue has been resolved:

![Screenshot 2023-04-07 110757](https://user-images.githubusercontent.com/124829903/230580083-a7b2c67d-2ae1-4c74-bb51-13b4d16fcf3b.jpg)
The cause of this duplication came from the array of logo names in which I had inserted the word Instagram twice

    <string-array name="logoList">
        <item>Logo</item>
        <item>Youtube</item>
        <item>Facebook</item>
        <item>WhatsApp</item>
        <item>Pinterest</item>
        <item>Twitter</item>
        <item>Linkedin</item>
        <item>Github</item>
        <item>Gmail</item>
        <item>Instagram</item>
        <item>Outlook</item>
        <item>Netflix</item>
        <item>Reddit</item>
        <item>Amazon</item>
        <item>Spotify</item>
        <item>Amazon Prime</item>
    </string-array>
